[tool.poetry]
package-mode=false

[tool.poetry.dependencies]
python="^3.11.9"
fastapi = {extras = ["all"], version = "^0.114.0"}
sqlalchemy = {extras = ["asyncio"], version = "^2.0.34"}
alembic = "^1.13.2"
black = "^24.8.0"
psycopg2 = "^2.9.9"
