"""create table TODOList and TODOItem

Revision ID: 9e29306ac831
Revises: 
Create Date: 2024-09-09 16:18:57.915944

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9e29306ac831"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "to_do_list",
        sa.Column("title", sa.String(length=50), nullable=False),
        sa.Column(
            "create_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_to_do_list")),
    )
    op.create_table(
        "to_do_item",
        sa.Column("title", sa.String(length=50), nullable=False),
        sa.Column("list_id", sa.Integer(), nullable=False),
        sa.Column("completed", sa.Boolean(), nullable=False),
        sa.Column(
            "create_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["list_id"],
            ["to_do_list.id"],
            name=op.f("fk_to_do_item_list_id_to_do_list"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_to_do_item")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("to_do_item")
    op.drop_table("to_do_list")
    # ### end Alembic commands ###
